In [1]:
list_out = [1,2,'three']
print(list_out)

[1, 2, 'three']


In [2]:
def calc(param1,param2):
    print(param1*param2,param1+param2)
    return  [param1*param2,param1+param2]

num1 = 10 
num2 = 5
ans = calc(num1,num2)
ans

50 15


[50, 15]

In [3]:
print('{greeting} {object}'.format(greeting = 'hello', object = 'world'))
li1 = ['one','two',3,]
li2 = [4,5,6]
print(li1.append(li2))#.append()は()内のものを'要素として'追加する
li3 = li1+li2
print(li3)#配列同士の結合

hello world
None
['one', 'two', 3, [4, 5, 6], 4, 5, 6]


In [5]:
li1 = ['one','two',3,]
li2 = [4,5,6]
print((li1.copy()).append(li2.copy()))#li1とli2を保存するため.copy()を用いた または、Tuplesを用いる方法もある
li3 = li1+li2
print(li3)#list.append()メソッドは、リストの末尾に引数として与えられた要素を追加しますが、戻り値はありません。そのため、li1.append(li2)自体の結果はNoneとなります。

None
['one', 'two', 3, 4, 5, 6]


In [6]:
li1 = ['one', 'two', 3]
li2 = [4, 5, 6]
li3 = li1.append(li2)
print(li3)
li4 = li1 + li2
print(li4)

None
['one', 'two', 3, [4, 5, 6], 4, 5, 6]


In [ ]:
li1 = ['one', 'two', 3]
li2 = [4, 5, 6]
li1.append(li2) #append()メソッドはリストを変更するだけで、新しいリストを返さないため、直接戻り値を取得することはできません
updated_li1 = li1  # 追加後のリストを新しい変数に代入
print(updated_li1)

['one', 'two', 3, [4, 5, 6]]


In [1]:
li1 = ['one', 'two', 3]
li2 = [4, 5, 6]
li1.append(li2)
li3 = li1  
print(li3)
li4 = li1 + li2
print(li4)
print(li1,li2)

['one', 'two', 3, [4, 5, 6]]
['one', 'two', 3, [4, 5, 6], 4, 5, 6]
['one', 'two', 3, [4, 5, 6]] [4, 5, 6]


In [1]:
li1 = ['one', 'two', 3]
li2 = [4, 5, 6]
li1_copy = li1.copy()
li1_copy.append(li2)
li3 = li1_copy  
print(li3)
li4 = li1 + li2
print(li4)


['one', 'two', 3, [4, 5, 6]]
['one', 'two', 3, 4, 5, 6]


In [1]:
def print_args(*args):
    for elem in args:
        print(elem)

print_args('java','python','c++') #関数の中では args にタプルで保存されているので，そこにアクセスすることで引数を取り出せます．


java
python
c++


In [4]:

def print_dict(**kwargs):
    print(kwargs)
print_dict(greeting= 'hello')#「keyword arguments 」の略で，引数がタプルではなくてdictionaryになります．argsがタプル，kwargsがkeywordつきのdictionaryと言ったイメージですね．関数を呼ぶときに function(param1=value1, param2=value2) という具合でkeywordとvalueを指定します．

{'greeting': 'hello'}


In [8]:
import numpy as np
np.__file__


'C:\\Users\\松本翔英\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\numpy\\__init__.py'

In [9]:
np_list1 = np.array([1,2,3])
np_list2 = np.array([[5,2,4], [9,2,3], [1,6,3]])
np_list3 = np.array([np.arange(3,31,2), [3,35,353,5,3,2,6,46,6,8,9,6,7,4]])
print(np_list1 * np_list2)
print((np_list1 * np_list2).shape)
li = np_list1 * np_list2
print(li[:,1:])
print(np_list3[1, 2:14:3])
print(np.arange(0, 5, 0.1))#例えばある閾値をたくさん用意してその結果がどう変わるか見る場合に，np.arange()で閾値のリストを作ることができる
print(np.linspace(1,3,50))#stepを指定したい時はnp.arange()で，stepはなんでもいいが特定の数だけほしいという場合はnp.linspace()が使える。stopの値を含むことに注意!


[[ 5  4 12]
 [ 9  4  9]
 [ 1 12  9]]
(3, 3)
[[ 4 12]
 [ 4  9]
 [12  9]]
[353   2   6   6]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
[1.         1.04081633 1.08163265 1.12244898 1.16326531 1.20408163
 1.24489796 1.28571429 1.32653061 1.36734694 1.40816327 1.44897959
 1.48979592 1.53061224 1.57142857 1.6122449  1.65306122 1.69387755
 1.73469388 1.7755102  1.81632653 1.85714286 1.89795918 1.93877551
 1.97959184 2.02040816 2.06122449 2.10204082 2.14285714 2.18367347
 2.2244898  2.26530612 2.30612245 2.34693878 2.3877551  2.42857143
 2.46938776 2.51020408 2.55102041 2.59183673 2.63265306 2.67346939
 2.71428571 2.75510204 2.79591837 2.83673469 2.87755102 2.91836735
 2.95918367 3.        ]


In [10]:
def add_world(hello):
    hello += ' world'
    return hello

h_str = 'hello'# immutable
h_list = ['h', 'e', 'l', 'l', 'o'] #mutable
output_str = add_world(h_str)#参照渡し(strだからh_str自体には2行目のhello += ' world'が反映されていない)
output_list = add_world(h_list)#値渡し(この時点でh_list自体に2行目のhello += ' world'が反映されている)
#''内の｛｝は . format()の返り値の代入場所(formatのメリットは文字列の結合部位を{}で指定できるところ)
print('output_str: {}'.format(output_str))#　immutable: int, float, bool, str, tuple
print('output_list: {}'.format(output_list))#　mutable: list, set, dict

print('h_str: {}'.format(h_str))
print('h_list: {}'.format(h_list))

ndarray = np.arange(0, 5)
ndarray_copy = ndarray.copy()
print("original array's id is {}".format(id(ndarray)))
print("copied array's id is {}".format(id(ndarray_copy)))

#changing original array
ndarray[:] = 100 #[:]はsliceのデフォルトの値で、行列全体が対象となっている
print('original array:\n', ndarray)
print('copied array:\n', ndarray_copy)

def change_hundred(array):

    array[0] = 100
    print(array)

def change_hundred_copy(array):
    
    array_copy = array.copy()
    array_copy[0] = 100
    print(array_copy)

array_1 = np.arange(0, 4)
array_2 = np.arange(0, 4)

output_array = change_hundred(array_1)
output_array_copy = change_hundred_copy(array_2)

print('original array_1:\n', array_1)#.copy()をとっておかないとオリジナルのarrayごと変更されてしまうので注意！
print('original array_2:\n', array_2)

output_str: hello world
output_list: ['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']
h_str: hello
h_list: ['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']
original array's id is 2330838686320
copied array's id is 2331010079632
original array:
 [100 100 100 100 100]
copied array:
 [0 1 2 3 4]
[100   1   2   3]
[100   1   2   3]
original array_1:
 [100   1   2   3]
original array_2:
 [0 1 2 3]


In [11]:
shape = (2, 3, 5)
zeros = np.zeros(shape) #いわゆる零行列をつくります．要素が全て0のndarrayです. shapeをタプルで渡しましょう． np.zeros(4) など，タプルではなくintegerを入れるとその数文の一列の零行列ができます．( [0, 0, 0, 0] 
print(zeros)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [12]:
shape = (2, 3, 5)
ones_array_1 = np.ones(shape)#np.zerosの「1」版です．全ての要素が「１」になります．
ones_array_2 = np.ones(4)

print(ones_array_1)
print(ones_array_2)

np.eye(3) #N x Nの単位行列を作ります．単位行列というのは対角成分が全て１となる正方行列です
np.eye(3, 5)#また， np.eye(N, M) とすると，N行M列の行列を作ることもできます．（滅多に使いませんが）


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[1. 1. 1. 1.]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [13]:
np.arange(0, 5, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [14]:
#0 ~ 1からランダムな数字で行列を作ることができます．引数を入れなければfloatが，引数の数によって返されるarrayの次元が変わります
random_float = np.random.rand()
random_1d = np.random.rand(3)
random_2d = np.random.rand(3, 4)

print('random_float: {}\n'.format(random_float))
print('random_1d: {}\n'.format(random_1d))
print('random_2d: {}\n'.format(random_2d))

random_float: 0.1745145145538196

random_1d: [0.40172919 0.24397585 0.94623347]

random_2d: [[0.35307266 0.47635144 0.92612002 0.73589975]
 [0.46557487 0.53226356 0.26572387 0.42052098]
 [0.09869821 0.2383009  0.89983605 0.54628872]]



In [15]:
#np.random.rand() が0 ~ 1からランダムな数字が返されるのに対し， np.random.randn() は標準正規分布(平均0, 分散1の正規分布)から値が返されます
random_float = np.random.randn()
random_1d = np.random.randn(3)
random_2d = np.random.randn(3, 4)

print('random_float: {}\n'.format(random_float))
print('random_1d: {}\n'.format(random_1d))
print('random_2d: {}\n'.format(random_2d))

random_float: -0.4512040460418405

random_1d: [ 0.93181368 -1.1888023  -0.73816372]

random_2d: [[-0.24969454  1.16321745  0.22405934 -0.42302541]
 [-0.17650149 -0.35609844 -1.17167254  1.2193511 ]
 [-0.83126331 -0.27016985  0.04200335  1.72950071]]



In [16]:
#これが，ランダム系で一番使うかもしれません．low以上hight未満のintegerからランダムに，指定したsizeのndarrayを返します．(sizeを指定しなかった場合はintegerを返す)
np.random.randint(10, 50, size=(2, 4, 3))
#実際にランダム値を使う時って，ランダムなindexが必要だったりと，0 ~ 1の間のランダム値よりも指定した範囲のintegerのランダム値を使うことの方が多いです．データサイエンス頻出です．

array([[[13, 22, 49],
        [38, 11, 12],
        [15, 45, 34],
        [47, 29, 18]],

       [[23, 38, 24],
        [43, 39, 35],
        [29, 44, 46],
        [37, 38, 30]]])

In [17]:
#.reshape(shape)超超超頻出です．あるndarrayのshapeを任意のshapeに変換(reshape)します．
#.reshape()によりもとのarrayは更新されません．新しいarrayが返されることに注意しましょう．
# また，新しいshapeはarrayの要素数と合ってないといけません．以下はエラーになります．
#li = np.arange(0,10)　要素数１０個
#new_shape = (2,3) 要素数６個
#reshaped_array = array.reshape(new_shape)　エラー
array = np.arange(0, 10)
print('array:\n{}'.format(array))
new_shape = (2, 5)
reshaped_array = array.reshape(new_shape)
print('reshaped array:\n{} '.format(reshaped_array))
print("reshaped array's is:\n{} ".format(reshaped_array.shape))
print('original array is NOT changed:\n{}'.format(array))

array:
[0 1 2 3 4 5 6 7 8 9]
reshaped array:
[[0 1 2 3 4]
 [5 6 7 8 9]] 
reshaped array's is:
(2, 5) 
original array is NOT changed:
[0 1 2 3 4 5 6 7 8 9]


In [22]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('array is:\n{}'.format(ndarray))
print("ndarray's shape is:\n{}".format(ndarray.shape))
expanded_ndarray = np.expand_dims(ndarray, axis=0)
expanded_ndarray.shape
print(expanded_ndarray)
squeezed_expanded_ndarray = np.squeeze(expanded_ndarray)
squeezed_expanded_ndarray.shape
print(squeezed_expanded_ndarray)

flatten_array = ndarray.flatten()
print('flatten_array:\n{}'.format(flatten_array))
print('ndarray:\n{}'.format(ndarray))


array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndarray's shape is:
(3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
flatten_array:
[1 2 3 4 5 6 7 8 9]
ndarray:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
ndarray = np.array([
    [1, 2, 3, 4],
    [10, 20, 30, 40],
    [100, 200, 300, 400],
])
np.save('saved_numpy.npy', ndarray)
loaded_numpy = np.load('saved_numpy.npy')
loaded_numpy

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])

In [1]:
import pandas as pd