In [ ]:
#➅
#import numpy as np  
# np.__file__
#array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# ➆
#INdex 
#ndarray = print(ndarray[1,2]) ６が表示される
#Slicing 
#[N:M] N以上M未満　[N:] N以上　
#[:, 2:] すべての行と３列目以降
#[N:M:L]とするとL-1飛びでslicingできる

#８
#np.arange([start,] stop[, step]) : start以上stop未満の値をstepずつ増加させた値のarrayを生成
#np.linspace(start, stop, num=50) : start以上stop未満の値を均等にnum個等分した値のarrayを生成
#.copy() : NumPy arrayをコピー
#np.zeros(shape) : 要素が全て０のndarrayを生成
#np.ones(shape) : 要素が全て１のndarrayを生成
#np.eye(N) : N x Nの単位行列を生成 単位行列というのは対角成分が全て１となる正方行列
#np.random.rand() : 0 ~ 1からランダムな数字で行列を生成
#np.random.randn() : 標準正規分布から値をとって行列を生成
#np.random.randint(low[, hight] [, size]) : low以上hight未満のintegerからランダムに，指定したsizeのndarrayを生成
#.reshape(shape) : ndarrayのshapeを任意のshapeに変換　
#reshape()によりもとのarrayは更新されず、新しいarrayが返される
#また，新しいshapeはarrayの要素数と合ってないとエラーになる
#
#補足　
#mutable: list, set, dict
#immutable: int, float, bool, str, tuple
#
#例1
#def add_world(hello):
#    hello += ' world'
#    return hello
#
#h_str = 'hello'
#h_list = ['h', 'e', 'l', 'l', 'o']
#output_str = add_world(h_str)
#output_list = add_world(h_list)

#print('output_str: {}'.format(output_str))
#print('output_list: {}'.format(output_list))

#print('h_str: {}'.format(h_str))
#print('h_list: {}'.format(h_list))
#
#表示結果1
#output_str: hello world
#output_list: ['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']
#h_str: hello
#h_list: ['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']
#

#例２
#def change_hundred(array):
#    array[0] = 100
#    return array

#def change_hundred_copy(array):
#    array_copy = array.copy()
#    array_copy[0] = 100
#    return array_copy

#array_1 = np.arange(0, 4)
#array_2 = np.arange(0, 4)

#output_array = change_hundred(array_1)
#output_array_copy = change_hundred_copy(array_2)

#print('original array_1:\n', array_1)
#print('original array_2:\n', array_2)

#表示結果2
#original array_1:
#[100   1   2   3]
#original array_2:
#[0 1 2 3]

#９
#.max()と.argmax() : ndarrayの最大値とそのindexを返す
#.min()と.argmin() : ndarrayの最小値とそのindexを返す
#.mean()：ndarrayの平均値を返す
#np.median(ndarray)：ndarrayの中央値を返す
#.std()：ndarrayの標準偏差を返す
#np.exp(ndarray)：ネイピア数の指数関数の結果を返す
#np.log(ndarray)：自然対数の結果を返す
#np.log10() や np.log2() で10や2を底にすることもできる
#np.nanとnp.isnan()：0で割った時などにnanが格納され，nanチェックにはnp.isnan()を用いる
#「nan」というのはNot-A-NumberでNoneとは違う
#np.e：ネイピア数(2.7182…)　ネイピア数が格納されている定数
#np.expand_dims(ndarray, axis)：rank(配列の次元数)を特定のaxisに追加
#np.squeeze(ndarray)：shapeで1になっている次元を削減
#.flatten()：一列にする もとのndarrayは変更されないことに注意
#np.save(‘パス’, ndarray): ndarrayを指定したパスに保存(.npyとして保存されることに注意！)
#np.load(‘パス’)：指定したパスの.npyファイルを読み込む
#
#



In [2]:
import numpy as np
np.__file__
loaded_numpy = np.load('saved_numpy.npy')
loaded_numpy

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])